const {_electron:electron,expect}=require('@playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const p=require('../electron/progression.cjs'),profile=require('../electron/profile.cjs');
const root=path.resolve(__dirname,'..');let app;
const capture=(page,options)=>process.env.FESTIVAL_EXECUTABLE?Promise.resolve():page.screenshot({...options,timeout:30000});
(async()=>{
  const qa=await fs.mkdtemp(path.join(root,'qa/v3-desktop-')),sample=await fs.readFile(path.join(root,'qa/cli-roundtrip.bin'));
  const original=profile.replaceState(sample,'PlayerWristbandSaveState',Buffer.from([1,0,0,0,2,0,0,0,0,1]));
  const fixture=path.join(qa,'C_ProfileData'),data=path.join(qa,'user-data');await fs.mkdir(data);await fs.writeFile(fixture,original);await fs.writeFile(fixture+'_SCopy',original);
  const env={...process.env,FESTIVAL_TEST_DATA:data,FESTIVAL_TEST_SCOPE:qa,FESTIVAL_TEST_HIDDEN:'1'};delete env.ELECTRON_RUN_AS_NODE;
  const launch=process.env.FESTIVAL_EXECUTABLE?{executablePath:process.env.FESTIVAL_EXECUTABLE,args:[]}:{args:[root]};const errors=[];
  app=await electron.launch({...launch,env,timeout:30000});const page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
  await app.evaluate(({shell})=>{global.__releaseCalls=0;global.__opened=[];global.fetch=async()=>{global.__releaseCalls++;return Response.json([{tag_name:'v0.4.0',name:'QA fixture · Journey update',body:'Isolated desktop verification only.\nRelease notes are displayed as plain text. <script>window.bad=true</script>',html_url:'https://github.com/ChefDavid0815/horizon-festival-toolkit/releases/tag/v0.4.0',draft:false,prerelease:false}])};shell.openExternal=async url=>{global.__opened.push(url)};});
  await expect(page.getByRole('combobox',{name:'Language / 语言'})).toBeEnabled();await page.getByRole('combobox',{name:'Language / 语言'}).selectOption('zh');
  await expect(page.getByRole('dialog',{name:'新版本，已抵达'})).toBeVisible({timeout:20000});
  await capture(page,{path:path.join(qa,'01-update-dialog-zh.png')});await page.getByRole('button',{name:'稍后再说',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.bad),undefined);assert.equal(await app.evaluate(()=>global.__releaseCalls),1);
  await page.getByRole('button',{name:'旅程进度 JOURNEY'}).click();await expect(page.getByRole('heading',{name:'让旅途，完整绽放。'})).toBeVisible();await expect(page.getByRole('button',{name:'拉满全部旅程',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'连接存档',exact:true}).click();await page.getByLabel('存档文件',{exact:true}).fill(fixture);await page.getByRole('button',{name:'连接并解密'}).click();await expect(page.getByText('本地存档已连接',{exact:true})).toBeVisible();
  await page.evaluate(()=>document.fonts.ready);await capture(page,{path:path.join(qa,'02-journey-zh.png'),animations:'disabled'});
  await page.getByRole('combobox',{name:'Language / 语言'}).selectOption('en');
  await page.getByRole('button',{name:/Photography/}).click();await page.getByRole('combobox',{name:'Progress filter'}).selectOption('remaining');
  const before=p.inspectProgression(original),photo=before.categories.find(c=>c.key==='photography_category'),item=photo.items.find(i=>!i.complete);
  await page.getByRole('button',{name:`Select item ${item.description.en||item.name.en}`,exact:true}).click();
  await page.getByRole('button',{name:'Back up & apply'}).click();await expect(page.getByText('Selected progress saved. An automatic backup is ready.')).toBeVisible({timeout:60000});
  const single=await fs.readFile(fixture);assert(p.inspectProgression(single).categories.find(c=>c.id===photo.id).items.find(i=>i.id===item.id).complete);assert(single.equals(await fs.readFile(fixture+'_SCopy')));
  await page.getByRole('button',{name:'Complete category',exact:true}).click();await page.getByRole('button',{name:'Back up & apply'}).click();await expect(page.getByRole('button',{name:'Back up & apply'})).toBeDisabled({timeout:60000});
  assert.equal(p.inspectProgression(await fs.readFile(fixture)).categories.find(c=>c.id===photo.id).points,photo.max);
  await page.getByRole('tab',{name:'Wristbands 03'}).click();await capture(page,{path:path.join(qa,'03-wristbands-en.png'),animations:'disabled'});
  await page.getByRole('button',{name:'Select wristband Orange',exact:true}).click();await page.getByRole('button',{name:'Back up & apply'}).click();await expect(page.getByRole('button',{name:'Back up & apply'})).toBeDisabled({timeout:60000});
  assert(p.inspectProgression(await fs.readFile(fixture)).wristbands.find(w=>w.id===5).owned);
  await page.getByRole('button',{name:'Complete all journeys',exact:true}).click();await page.getByRole('button',{name:'Back up & apply'}).click();await expect(page.getByRole('button',{name:'Back up & apply'})).toBeDisabled({timeout:60000});
  const completed=p.inspectProgression(await fs.readFile(fixture));assert(completed.campaigns.every(c=>c.points===c.max&&c.completed===c.total));assert(completed.wristbands.every(w=>w.owned));
  await page.getByRole('button',{name:'Backups & restore'}).click();await page.getByRole('button',{name:'Restore version'}).last().click();await page.getByRole('button',{name:'Restore save',exact:true}).click();await expect(page.getByText('Save restored. The previous version was also backed up. Reconnect to view the result.')).toBeVisible({timeout:30000});assert((await fs.readFile(fixture)).equals(original));
  await page.getByRole('button',{name:'Content updates'}).click();await expect(page.getByRole('heading',{name:'Product release history'})).toBeVisible();await page.getByRole('button',{name:'View update',exact:true}).click();await expect(page.getByRole('dialog',{name:'A new version has arrived'})).toBeVisible();await page.getByRole('button',{name:'Download on GitHub'}).click();assert.deepEqual(await app.evaluate(()=>global.__opened),['https://github.com/ChefDavid0815/horizon-festival-toolkit/releases/tag/v0.4.0']);
  await capture(page,{path:path.join(qa,'04-history-en.png'),animations:'disabled'});
  await page.getByRole('button',{name:/V0.2.0/}).click();await expect(page.getByText('Search 647 cars, add copies and fill missing models.')).toBeVisible();
  await page.getByRole('button',{name:'Journey progress'}).click();await page.setViewportSize({width:1106,height:744});await page.getByRole('tab',{name:'Wristbands 03'}).click();
  const minimum=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,navOverflow:document.querySelector('.main-nav').scrollWidth>document.querySelector('.main-nav').clientWidth}));assert(!minimum.overflow&&!minimum.navOverflow,JSON.stringify(minimum));
  await capture(page,{path:path.join(qa,'05-minimum-window.png'),animations:'disabled'});
  await page.getByRole('tab',{name:'DISCOVER JAPAN 01'}).click();await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.orbit-line.two').evaluate(e=>getComputedStyle(e).animationName),'none');
  const security=await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return{nodeIntegration:w.nodeIntegration,contextIsolation:w.contextIsolation,sandbox:w.sandbox}});assert.deepEqual(security,{nodeIntegration:false,contextIsolation:true,sandbox:true});
  await app.close();app=null;
  app=await electron.launch({...launch,env,timeout:30000});const restart=await app.firstWindow();await expect(restart.getByRole('combobox',{name:'Language / 语言'})).toBeEnabled();await restart.waitForTimeout(3200);assert.equal(await restart.getByRole('dialog').count(),0);assert.equal((await restart.evaluate(()=>window.festival.state())).summary,null);
  await app.close();app=null;assert.deepEqual(errors,[]);
  const report={passed:true,version:'0.3.0',checks:['automatic update dialog','daily cache across restart','release notes plain-text safety','allowlisted GitHub link','38 categories / 2833 items','single item write','whole category write','individual wristband','complete both journals and all wristbands','SCopy equality','byte-exact backup restore','bilingual UI','history accordion','minimum window','reduced motion','sandbox'],minimum,security,formalSaveAccess:false,fixtureProgressWrites:true,inGameVerified:false,rendererErrors:errors};await fs.writeFile(path.join(qa,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({qa,...report},null,2));
})().catch(async e=>{console.error(e);if(app)await app.close().catch(()=>{});process.exitCode=1});
