const {_electron:electron,expect}=require('@playwright/test');
const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
const profile=require('../electron/profile.cjs');
const garage=require('../electron/garage.cjs');
const root=path.resolve(__dirname,'..');
let app;
(async()=>{
  const qa=await fs.mkdtemp(path.join(root,'qa/v2-desktop-'));
  const sample=await fs.readFile(path.join(root,'qa/cli-roundtrip.bin'));
  const fixture=path.join(qa,'C_ProfileData');
  await fs.writeFile(fixture,sample);await fs.writeFile(fixture+'_SCopy',sample);
  const env={...process.env,FESTIVAL_TEST_DATA:path.join(qa,'user-data'),FESTIVAL_TEST_SCOPE:qa,FESTIVAL_TEST_HIDDEN:'1'};delete env.ELECTRON_RUN_AS_NODE;
  const launch=process.env.FESTIVAL_EXECUTABLE?{executablePath:process.env.FESTIVAL_EXECUTABLE,args:[]}:{args:[root]};
  const errors=[];
  async function open(){app=await electron.launch({...launch,env,timeout:30000});const page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await expect(page.getByRole('combobox',{name:'Language / 语言'})).toBeEnabled();return page;}
  let page=await open();
  console.log('Checking desktop UI, car writes, recovery and catalog import');
  await page.getByRole('combobox',{name:'Language / 语言'}).selectOption('zh');
  await page.evaluate(()=>document.fonts.ready);
  assert.equal((await page.evaluate(()=>window.festival.state())).summary,null);
  if(!process.env.FESTIVAL_EXECUTABLE)await page.screenshot({path:path.join(qa,'01-playlist-zh.png'),animations:'disabled'});
  await page.getByRole('button',{name:'车辆收藏 GARAGE'}).click();
  await expect(page.getByRole('heading',{name:'把梦想，开进车库。'})).toBeVisible();
  if(!process.env.FESTIVAL_EXECUTABLE)await page.screenshot({path:path.join(qa,'02-garage-zh.png'),animations:'disabled'});
  await page.getByRole('textbox',{name:'搜索车辆'}).fill('丰田 2000GT');
  await expect(page.locator('.car-card')).toHaveCount(1);
  await page.getByRole('textbox',{name:'搜索车辆'}).fill('xyz-no-match');await expect(page.getByText('没有找到匹配车型')).toBeVisible();
  await page.getByRole('combobox',{name:'Language / 语言'}).selectOption('en');
  await page.getByRole('textbox',{name:'Search cars'}).fill('Toyota 2000GT');await expect(page.locator('.car-card')).toHaveCount(1);
  await page.getByRole('button',{name:'Connect save',exact:true}).click();await page.getByLabel('Save file',{exact:true}).fill(fixture);await page.getByRole('button',{name:'Connect & decrypt'}).click();
  await expect(page.getByText('Local save connected',{exact:true})).toBeVisible({timeout:30000});assert((await fs.readFile(fixture)).equals(sample));
  const before=await garage.inspectGarage(sample);
  await page.getByRole('button',{name:'Add 2000GT',exact:true}).click();await page.getByRole('button',{name:'Add 2000GT',exact:true}).click();
  await expect(page.locator('.car-add b')).toHaveText('2');
  await page.getByRole('button',{name:'Back up & apply'}).click();
  await expect(page.getByText('Selected playlist progress and car inventory saved. An automatic backup is ready.')).toBeVisible({timeout:60000});
  const carEdited=await fs.readFile(fixture),after=await garage.inspectGarage(carEdited);assert.equal(after.total,before.total+2);assert.equal(after.counts[247],(before.counts[247]||0)+2);assert(carEdited.equals(await fs.readFile(fixture+'_SCopy')));
  await page.getByRole('button',{name:'Add all missing cars'}).click();await page.getByRole('button',{name:'Back up & apply'}).click();
  await expect(page.getByRole('button',{name:'Back up & apply'})).toBeDisabled({timeout:60000});
  const allAdded=await fs.readFile(fixture);assert.equal((await garage.inspectGarage(allAdded)).missing.length,0);
  await page.getByRole('button',{name:'Add all missing cars'}).click();await expect(page.getByRole('button',{name:'Back up & apply'})).toBeDisabled();
  await page.getByRole('button',{name:'Clear car selection'}).click();
  await page.getByRole('button',{name:'Seasonal playlist'}).click();
  await page.getByRole('tab',{name:/S5/}).click();await page.getByRole('button',{name:'Select S5 week 2 Autumn'}).click();
  await page.getByRole('button',{name:'Back up & apply'}).click();await expect(page.getByRole('button',{name:'Back up & apply'})).toBeDisabled({timeout:60000});
  const seasonEdited=await fs.readFile(fixture);assert(profile.inspectSeasons(seasonEdited).find(w=>w.key==='5:1').complete);
  const a=profile.parse(allAdded),b=profile.parse(seasonEdited);assert(allAdded.subarray(a.database.start,a.database.end).equals(seasonEdited.subarray(b.database.start,b.database.end)));
  await page.getByRole('button',{name:'Backups & restore'}).click();
  await page.getByRole('button',{name:'Restore version'}).last().click();await page.getByRole('button',{name:'Restore save',exact:true}).click();
  await expect(page.getByText('Save restored. The previous version was also backed up. Reconnect to view the result.')).toBeVisible({timeout:30000});assert((await fs.readFile(fixture)).equals(sample));
  await page.getByRole('button',{name:'Content updates'}).click();
  if(!process.env.FESTIVAL_EXECUTABLE)await page.screenshot({path:path.join(qa,'03-updates-en.png'),animations:'disabled'});
  const seasons=structuredClone(profile.seasons);seasons.weeks=seasons.weeks.filter(w=>w.series===5).map(w=>({...w,series:6,key:`6:${w.week}`,title:'QA SERIES SIX'}));
  const packFile=path.join(qa,'future-content.json');await fs.writeFile(packFile,JSON.stringify({format:'festival-catalog',version:2,resourceBuild:'synthetic-S6',seasons}));
  await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},packFile);
  await page.getByRole('button',{name:'Import content pack'}).click();await expect(page.getByText('Content catalog updated. Selections cleared to use the latest data.')).toBeVisible();
  await page.getByRole('button',{name:'Seasonal playlist'}).click();await page.getByRole('tab',{name:/S6/}).click();
  await expect(page.getByRole('button',{name:'Select S6 week 1 Summer'})).toBeVisible();
  await page.setViewportSize({width:1106,height:744});
  const layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,cardBottom:document.querySelectorAll('.week-card')[3].getBoundingClientRect().bottom,dockTop:document.querySelector('.action-dock').getBoundingClientRect().top}));assert(!layout.overflow);assert(layout.cardBottom<layout.dockTop,JSON.stringify(layout));
  await page.emulateMedia({reducedMotion:'reduce'});const motion=await page.locator('.festival-layout').evaluate(e=>getComputedStyle(e).animationName);assert.equal(motion,'none');
  const security=await app.evaluate(({BrowserWindow})=>{const p=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return {nodeIntegration:p.nodeIntegration,contextIsolation:p.contextIsolation,sandbox:p.sandbox};});assert.deepEqual(security,{nodeIntegration:false,contextIsolation:true,sandbox:true});
  await page.getByRole('combobox',{name:'Language / 语言'}).selectOption('zh');
  let autoSyncTested=false;
  if(process.env.FESTIVAL_RESOURCE_FIXTURE){
    const game=path.join(qa,'game');await fs.mkdir(path.join(game,'media/Stripped'),{recursive:true});
    for(const file of ['media/ObjectModelGame.zip','media/Stripped/gamedbRC.slt'])await fs.copyFile(path.join(process.env.FESTIVAL_RESOURCE_FIXTURE,file),path.join(game,file));
    await page.evaluate(gamePath=>window.festival.contentSettings({gamePath,autoSync:true,allowOnline:false}),game);
  }
  await app.close();app=null;page=await open();
  if(process.env.FESTIVAL_RESOURCE_FIXTURE){await expect.poll(async()=>(await page.evaluate(()=>window.festival.state())).content.source,{timeout:20000}).toBe('game');autoSyncTested=true;}
  const restarted=await page.evaluate(()=>window.festival.state());assert.equal(restarted.language.preference,'zh');assert.equal(restarted.catalog.weeks.length,24);assert.equal(restarted.summary,null);
  await app.close();app=null;assert.deepEqual(errors,[]);
  const report={passed:true,version:restarted.version,executable:launch.executablePath||'development Electron',checks:['Chinese make search','English search','empty search','single car quantity +2','add all missing','idempotent collection','season-only preserves garage','backup restore','S6 data pack import','catalog restart persistence','language persistence','minimum window layout','reduced motion','sandbox'],autoSyncTested,layout,security,formalSaveAccess:false,fixtureCarWrites:true,inGameVerified:false,rendererErrors:errors};
  await fs.writeFile(path.join(qa,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({qa,...report},null,2));
})().catch(async e=>{console.error(e);if(app)await app.close().catch(()=>{});process.exitCode=1;});
