import {useState,useMemo,useEffect} from 'react';
import {Compass,ArrowUpRight,Check,CheckCheck,Search,ChevronRight,ChevronLeft,Sparkles,Award,MapPin,Flag,RotateCcw} from 'lucide-react';
import {useI18n} from './Language.jsx';
const colors={1:'#efd752',5:'#f2984f',2:'#a7cc65',3:'#82c1db',6:'#ae93d9',4:'#e798be',7:'#cbb06c'};
const order=[1,5,2,3,6,4,7];
export default function Journey({catalog,summary,queue,setQueue,wristQueue,setWristQueue,busy}){
  const {t,locale}=useI18n(),[path,setPath]=useState('discovery'),[category,setCategory]=useState(null),[query,setQuery]=useState(''),[page,setPage]=useState(0),[filter,setFilter]=useState('all');
  const journey=summary?.journey,loaded=!!summary;
  const campaigns=journey?.campaigns.length?journey.campaigns:catalog?.campaigns||[];
  const categories=journey?.categories.length?journey.categories:(catalog?.categories||[]).map(c=>({...c,total:c.items.length,completed:0,items:c.items.map(id=>catalog.items.find(i=>i.id===id))}));
  const campaign=campaigns.find(c=>c.key===path),availableCategories=categories.filter(c=>campaign?.categories.includes(c.id));
  const current=availableCategories.find(c=>c.id===category)||availableCategories[0];
  const selected=new Set(queue),bands=new Set(wristQueue);
  const label=v=>v?.[locale]||v?.en||'';
  const canEdit=loaded&&!journey?.collectionError&&!busy;
  const matching=useMemo(()=>{const q=query.trim().toLocaleLowerCase();return (current?.items||[]).filter(i=>(!q||[label(i.name),label(i.description),i.id].join(' ').toLocaleLowerCase().includes(q))&&(filter!=='remaining'||!i.complete)&&(filter!=='selected'||selected.has(i.id)));},[current,query,filter,queue,locale]);
  useEffect(()=>setPage(0),[query,filter,category,path,summary]);
  const pages=Math.max(1,Math.ceil(matching.length/36)),activePage=Math.min(page,pages-1),shown=matching.slice(activePage*36,(activePage+1)*36);
  const add=items=>setQueue(q=>[...new Set([...q,...items.filter(i=>i.available&&!i.complete).map(i=>i.id)])]);
  const toggle=id=>setQueue(q=>q.includes(id)?q.filter(x=>x!==id):[...q,id]);
  const pathItems=availableCategories.flatMap(c=>c.items),pending=pathItems.filter(i=>selected.has(i.id)).length;
  const percent=campaign?.total?Math.round(100*campaign.completed/campaign.total):0;
  return <div className="journey view-enter">
    <section className="page-intro"><div><div className="eyebrow">EVERY MILE. EVERY MILESTONE.</div><h1>{t('让旅途，完整绽放')}<span>{t('。')}</span></h1><p>{t('探索日本、点亮嘉年华，把每一份热爱收入收藏手册。')}</p></div><div className="intro-actions"><span className="edition-pill"><Compass size={15}/> THE JOURNEY / 03</span><button className="small-btn" disabled={!canEdit||!!journey?.wristbandError} onClick={()=>{add(categories.flatMap(c=>c.items));setWristQueue((journey?.wristbands||[]).filter(w=>!w.owned).map(w=>w.id))}}><CheckCheck size={15}/>{t('拉满全部旅程')}</button></div></section>
    <div className="journey-paths" role="tablist" aria-label={t('旅程分类')}>
      {[['discovery','DISCOVER JAPAN',Compass],['festival',t('地平线嘉年华'),Flag],['wristbands',t('腕带收藏'),Award]].map(([key,name,Icon])=><button role="tab" aria-selected={path===key} key={key} className={path===key?'active':''} onClick={()=>{setPath(key);setQuery('');setFilter('all')}}><Icon size={17}/>{name}<span>{key==='discovery'?'01':key==='festival'?'02':'03'}</span></button>)}
    </div>
    {path!=='wristbands'?<>
      <section className={`journey-hero ${path}`}>
        <div className="journey-hero-copy"><span className="journey-kicker"><span/>{path==='discovery'?'THE ART OF EXPLORATION':'THE SPIRIT OF THE FESTIVAL'}</span><h2>{path==='discovery'?<>DISCOVER<br/><em>JAPAN.</em></>:<>CHASE YOUR<br/><em>HORIZON.</em></>}</h2><p>{label(campaign?.name)}<span> / {availableCategories.length} {t('个分类')}</span></p><div className="journey-hero-actions"><button className="small-btn" disabled={!canEdit} onClick={()=>add(pathItems)}><Sparkles size={15}/>{t('拉满整个进度')}<ArrowUpRight size={15}/></button><span>{pending? t('已选择 {0} 项',[pending]):t('你的下一站，由你决定')}</span></div></div>
        <div className="journey-orbit" aria-hidden="true"><div className="orbit-line one"/><div className="orbit-line two"/><div className="orbit-grid"/><Compass size={210} strokeWidth={.4}/><span className="orbit-coordinate">35°40′ N<br/>139°45′ E</span><span className="orbit-ticket">HORIZON<br/><b>{path==='discovery'?'日本':'FESTIVAL'}</b><small>COLLECTION JOURNAL</small></span></div>
        <div className="journey-hero-stats"><div className="journey-ring" style={{'--progress':`${loaded?percent:0}%`}}><div><b>{loaded?percent:'—'}<small>%</small></b><span>{t('收藏完成度')}</span></div></div><div className="journey-totals"><span><b>{loaded?(campaign?.completed??'—'):'—'}</b> / {campaign?.total??pathItems.length} {t('项')}</span><span><b>{loaded?(campaign?.points??'—').toLocaleString():'—'}</b> / {campaign?.max?.toLocaleString()} PTS</span></div></div>
      </section>
      {journey?.collectionError?<div className="message error" role="alert">{t(journey.collectionError)}</div>:null}
      {!loaded?<div className="journal-connect-note"><MapPin size={17}/>{t('连接存档后显示真实进度，并可选择要拉满的项目。')}</div>:null}
      <div className="journal-layout"><aside className="journal-categories" aria-label={t('进度分类')}><div className="section-label">{t('收藏目录')}<span>{String(availableCategories.length).padStart(2,'0')}</span></div>{availableCategories.map((c,i)=><button key={c.id} className={current?.id===c.id?'active':''} onClick={()=>{setCategory(c.id);setQuery('')}}><span className="category-number">{String(i+1).padStart(2,'0')}</span><span className="category-title">{label(c.name)}<small>{loaded?`${c.completed} / ${c.total}`:`${c.total} ${t('项')}`}</small></span><span className="category-mini" style={{'--progress':`${loaded?c.completed/c.total*100:0}%`}}/>{queue.some(id=>c.items.some(i=>i.id===id))?<i/>:null}</button>)}</aside>
      <section className="journal-panel" key={current?.id}><div className="journal-panel-heading"><div><span className="eyebrow">THE COLLECTION</span><h2>{label(current?.name)}</h2><p>{loaded?`${current?.points?.toLocaleString()??'—'} / ${current?.max?.toLocaleString()} PTS`:t('等待连接存档')}</p></div><button className="small-btn" disabled={!canEdit} onClick={()=>add(current?.items||[])}><CheckCheck size={16}/>{t('拉满此分类')}</button></div>
      <div className="journal-toolbar"><label className="search-input"><Search size={17}/><input aria-label={t('搜索进度项目')} placeholder={t('搜索项目、挑战或地点')} value={query} onChange={e=>setQuery(e.target.value)}/>{query?<button onClick={()=>setQuery('')} aria-label={t('清空搜索')}>×</button>:null}</label><select aria-label={t('进度筛选')} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t('全部项目')}</option><option value="remaining">{t('未完成')}</option><option value="selected">{t('已选择')}</option></select></div>
      <div className="journal-list-caption"><span>{t('项目 / 完成记录')}</span><button className="text-btn" onClick={()=>add(matching)} disabled={!canEdit||!matching.length}>{t('选择筛选结果')}</button></div>
      <div className="journal-items">{shown.map((item,i)=><button style={{'--row':Math.min(i,8)}} key={item.id} className={`journal-item ${selected.has(item.id)?'selected':''} ${item.complete?'complete':''}`} aria-pressed={selected.has(item.id)} aria-label={`${t('选择项目')} ${label(item.description)||label(item.name)}`} disabled={!canEdit||!item.available||item.complete} onClick={()=>toggle(item.id)}><span className="journal-check">{item.complete?<Check size={14}/>:selected.has(item.id)?<Check size={15}/>:<span/>}</span><span className="journal-item-copy"><strong>{label(item.name)}</strong><small>{label(item.description)||item.id}</small></span><span className="journal-item-score"><b>+{item.points}</b><small>{item.complete?t('已完成'):selected.has(item.id)?t('待应用'):loaded?t('未完成'):t('未连接')}</small></span><ChevronRight size={14}/></button>)}</div>
      {!shown.length?<div className="empty search-empty"><Search size={28}/><p>{t('没有匹配的进度项目')}</p></div>:null}
      <div className="pagination"><span>{t('共 {0} 项',[matching.length])}</span><button className="small-btn" aria-label={t('上一页')} disabled={!activePage} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={15}/></button><b>{activePage+1} / {pages}</b><button className="small-btn" aria-label={t('下一页')} disabled={activePage+1>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={15}/></button></div></section></div>
    </>:<section className="wristband-workspace"><div className="wristband-heading"><div><span className="eyebrow">EARN YOUR COLOURS.</span><h2>{t('七种色彩，一段传奇。')}</h2><p>{t('读取腕带持有记录，选择单条腕带或一次补齐全部颜色。')}</p></div><button className="primary" disabled={!loaded||busy||!!journey?.wristbandError} onClick={()=>setWristQueue((journey?.wristbands||[]).filter(w=>!w.owned).map(w=>w.id))}><Sparkles size={17}/>{t('补齐全部腕带')}</button></div>
      {journey?.wristbandError?<div className="message error">{t(journey.wristbandError)}</div>:null}
      <div className="wristband-grid">{order.map((id,i)=>{const band=journey?.wristbands.find(w=>w.id===id)||catalog?.wristbands.find(w=>w.id===id);return <button key={id} className={`wristband-card ${bands.has(id)?'selected':''}`} style={{'--band':colors[id],'--row':i}} disabled={!loaded||busy||!!journey?.wristbandError||band?.owned} onClick={()=>setWristQueue(q=>q.includes(id)?q.filter(x=>x!==id):[...q,id])} aria-pressed={bands.has(id)} aria-label={`${t('选择腕带')} ${t(band?.name||'')}`}><span className="wristband-index">0{i+1}</span><div className="wristband-object"><span>HORIZON</span><b>H</b><i>FESTIVAL / JAPAN</i></div><strong>{t(band?.name||'')}</strong><small>{band?.owned?<><Check size={13}/>{t('已拥有')}</>:bands.has(id)?t('待应用'):loaded?t('未拥有'):t('未连接')}</small></button>})}</div><p className="subtle-note">{t('腕带持有记录与赛事资格、剧情解锁是不同记录；此处只修改腕带持有记录。')}</p></section>}
    <div className="journey-bottom-note"><span>{t('编辑收藏记录与积分；游戏内奖励及解锁效果仍需验证。')}</span><button className="text-btn" disabled={busy||(!queue.length&&!wristQueue.length)} onClick={()=>{setQueue([]);setWristQueue([])}}><RotateCcw size={13}/>{t('清空进度选择')}</button></div>
  </div>;
}
