import {useState} from 'react';
import {ArrowUpRight,RefreshCw,History,Sparkles,CheckCircle2,Download,ChevronDown} from 'lucide-react';
import {useI18n} from './Language.jsx';
const history=[
  {version:'0.3.0',date:'2026.09.22',title:'每一段旅程，都值得收藏。',en:'Every journey deserves a place.',tag:'THE JOURNEY UPDATE',items:['每日 GitHub 已发布版本检查与下载提醒。','Discover Japan 与嘉年华收藏手册：38 个分类、2,833 个子项目。','单项、分类或整个进度选择；积分同步写回，自动备份。','七色腕带持有记录读取与补齐。','统一交互动效、旅程界面与双语版本历史。']},
  {version:'0.2.0',date:'2026.09.20',title:'把梦想，开进车库。',en:'Bring your dream garage home.',tag:'THE COLLECTION UPDATE',items:['647 款车辆搜索、单车加库存与补齐缺失车型。','本地游戏资源同步、独立内容数据包。','游戏内系列赛封面、收藏工作区与细腻动效。']},
  {version:'0.1.1',date:'2026.09.18',title:'你的嘉年华，从这里开始。',en:'Your festival starts here.',tag:'THE FIRST CHAPTER',items:['S1–S5 季节赛进度与积分编辑。','写入前备份、SCopy 同步与恢复。','简体中文、English 与系统语言偏好。']},
];
export default function ReleaseCenter({releases,setReleases,showRelease,busy,api,action}){
  const {t,locale}=useI18n(),[checking,setChecking]=useState(false),[expanded,setExpanded]=useState('0.3.0');
  const check=async()=>{setChecking(true);try{await action(async()=>{const r=await api.checkRelease();setReleases(r);if(r.available)showRelease()})}finally{setChecking(false)}};
  return <div className="release-center"><section className="client-release-panel"><div className="client-release-mark"><Sparkles size={28}/><span>03</span></div><div className="client-release-copy"><span className="eyebrow">FESTIVAL TOOLKIT / WINDOWS</span><h2>{t('每一次更新，都让旅途更好。')}</h2><p>{t('当前版本')} <b>{releases?.currentVersion||'0.3.0'}</b><i/> {t('每日自动检查 GitHub Release')}</p><span className={`release-status ${releases?.status==='offline'?'offline':''}`} role="status"><CheckCircle2 size={13}/>{t(checking?'正在检查更新…':releases?.status==='offline'?'暂时无法连接 GitHub，请稍后重试。':releases?.available?'发现新版本':releases?.status==='ok'?'你已是最新版本':'等待首次检查')}{releases?.checkedAt&&!checking?<small>{new Date(releases.checkedAt).toLocaleString(locale==='zh'?'zh-CN':'en-US')}</small>:null}</span></div><div className="client-release-actions"><button className="primary" disabled={busy||checking} onClick={releases?.available?showRelease:check}>{releases?.available?<Download size={16}/>:<RefreshCw size={16} className={checking?'spin':''}/>} {t(releases?.available?'查看新版本':'检查更新')}<ArrowUpRight size={16}/></button><button className="text-btn" onClick={()=>action(()=>api.openRelease())} disabled={busy}>{t('GitHub 发布页面')}<ArrowUpRight size={13}/></button></div></section>
    <section className="release-history"><div className="history-heading"><History size={17}/><h2>{t('产品历史更新记录')}</h2><span>THE STORY SO FAR</span></div>{history.map((r,i)=><article key={r.version} className={`history-entry ${expanded===r.version?'expanded':''}`}><div className="history-rail"><span/>{i<history.length-1?<i/>:null}</div><div className="history-content"><button className="history-toggle" aria-expanded={expanded===r.version} aria-controls={`history-${r.version}`} onClick={()=>setExpanded(v=>v===r.version?'':r.version)}><time>{r.date}</time><b>V{r.version}</b><strong>{locale==='zh'?r.title:r.en}</strong>{!i?<em>{t('当前版本')}</em>:null}<ChevronDown size={16}/></button><div className="history-detail" id={`history-${r.version}`} hidden={expanded!==r.version}><span>{r.tag}</span><ul>{r.items.map(item=><li key={item}>{t(item)}</li>)}</ul>{!i?<p>{t('编辑收藏记录与积分；游戏内奖励及解锁效果仍需验证。')}</p>:null}</div></div></article>)}</section>
  </div>
}
